server:
  port: 8090
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
spring:
  application:
    name: gateway-client
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: item-service
          uri: lb://item-service
          predicates:
            - "Path=/api/v1/items/**"
#          filters:
#            - TokenRelay=
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/market-realm
          jwk-set-uri: http://localhost:8080/realms/market-realm/protocol/openid-connect/certs
#      client:
#        registration:
#          gateway:
#            client-id: market-keycloak
#            client-secret: WG7nUka6Dnx6Zl6XtPq8Oar4gpfj2Pon
#            provider: keycloak
#            authorization-grant-type: authorization_code
#            redirect_uri: "http://localhost:8090/login/oauth2/code/{registrationId}"
#            scope: openid
#        provider:
#          keycloak:
#            issuer-uri: "http://localhost:8080/realms/market-realm"

