server:
  port: 8090
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: gateway-client
  cloud:
#    loadbalancer:
#      ribbon:
#        enabled: false
    gateway:
#      discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: true
      routes:
         - id: users-service-route
           uri: lb://user-service
           predicates:
           - Path=/api/v1/users/**
           filters:
           - TokenRelay=
         - id: product-service-route
           uri: lb://product-service
           predicates:
           - Path=/api/v1/categories/**, /api/v1/products/**, /api/v1/conditions/**
           filters:
           - TokenRelay=
  security:
    oauth2:
      client:
        registration:
          gateway:
            provider: my-provider
            client-id: gateway-client-id
            client-secret: my-secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://backend-gateway-client:8090/login/oauth2/code/{registrationId}"
            scope: openid, message.read
        provider:
          my-provider:
            issuer-uri: http://backend-auth:8081

