server:
  port: 8083
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user-service-db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1234
  rabbitmq:
    port: 5672
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  cloud:
    config:
      enabled: false