spring:
  profiles:
    active: dev
  application:
    name: user-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://backend-auth:8081

management:
  endpoints:
    web:
      exposure:
        include:
          - busrefresh
          - refresh


