server:
  port: 8082
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/item-service-db
    username: postgres
    password: 1234
  rabbitmq:
    port: 5672
  cloud:
    config:
      enabled: false
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
management:
  endpoints:
    web:
      exposure:
        include:
          - busrefresh
          - refresh

product:
  status:
    defaultStatus: MODERATION

