server:
  port: 8083

spring:
  application:
    name: item-service
  datasource:
    url: jdbc:postgresql://localhost:5432/item-service-db
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/market-realm
          jwk-set-uri: http://localhost:8080/realms/market-realm/protocol/openid-connect/certs



